tags:
  - Tasks
summary: Delete a task
parameters:
  - in: path
    name: task_id
    required: true
    type: integer
responses:
  204:
    description: Task deleted
  404:
    description: Task not found
  401:
    description: Unauthorized