tags:
  - Tasks
summary: Create a new task
parameters:
  - in: body
    name: body
    schema:
      $ref: '#/definitions/Task'
responses:
  201:
    description: Task created
    schema:
      $ref: '#/definitions/Task'
  401:
    description: Unauthorized