[tool.ruff]
line-length = 100
indent-width = 2
select = [
  "E",
  "F",
  "I",
] # Reglas específicas (E = pycodestyle, F = pyflakes, I = isort)
ignore = [
  "E501",
] # Ignorar reglas específicas (ej. E501 = línea demasiado larga)
